namespace ServerClient
{
    public enum MessageType : byte { HANDSHAKE, TABLE_REQUEST, TABLE, ROLE, GENERATE,
        VALIDATE_MOVE, MOVE,
        LOOT_PICKUP, LOOT_PICKUP_BROADCAST,
        VALIDATE_TELEPORT, FREEZE_ITEM, FREEZING_SUCCESS, UNFREEZE_ITEM, CONSUME_FROZEN_ITEM, TELEPORT, LOOT_CONSUMED
    };
    public enum MoveValidity { VALID, BOUNDARY, OCCUPIED_PLAYER, OCCUPIED_WALL, TELEPORT };
}
